Resource count endpoint
projecttacoma/deqm-test-server pull request #110
Opened 2022-06-14 20:50 UTC by sakhin123

# Summary
We added API endpoints to do a resource count, and return a key:value pair of resourceTypes and their counts. 
## New behavior
New endpoint exists that gets a key:value pair of resourceTypes and their counts. 
## Code changes

Code changes made to:
- database/dbOperations.js, server/server.js and new files created to handle the new endpoint
- controllers/resourcecount.controller.js
- new function getAllResourceCounts() that retrieves all resource counts from db, then formats and returns them as key:value pairs
- services/resourcecount.service.js
- test/services/resourcecount.service.test.js

# Testing guidance
- GET request: http://localhost:3000/4_0_1/resourceCount
- Run unit tests

2022-06-15 15:17 UTC, sarahmcdougall requested changes
Great work on this task! :) I tested the endpoint in Insomnia and received accurate counts of the resources in my database. Also ran all the unit tests and they pass.

I don't have any suggested changes regarding functionality - everything seems good there. Just have a few comments on descriptions/documentation for you to take a look at. I also think this branch needs a good ol' rebase - I saw some `meta.lastUpdated` code and I think it's from a previous PR that recently got merged.

2022-06-15 19:15 UTC, sakhin123 commented on src/database/dbOperations.js
> + * @param {*} resourceType specifies the name of the collection to be counted
Changed

2022-06-16 14:45 UTC, sakhin123 commented on test/services/resourcecount.service.test.js
> +  beforeAll(() => {
Changed

2022-06-16 14:48 UTC, sakhin123 commented on test/services/base.service.test.js
> +  meta: { lastUpdated: '1900-01-01T00:00:00Z' },
👵🏼

2022-06-16 18:39 UTC, sarahmcdougall approved these changes

2022-06-16 18:39 UTC, merged