Status location
projecttacoma/deqm-test-server pull request #19
Opened 2021-09-27 15:19 UTC by natjoe4

# Summary
Deqm-test-server now responds with a 202 status code and a content location header when sent a submit-data request with the prefer header set to respond-async.

## New behavior
When sending a submit-data request with the prefer header set to 'respond-async', a barebones bulk data import function is now called which returns a 202 status code and a (hard-coded for now) content location to query for import status updates. The user can now send follow-up get requests to that endpoint and receive a 501 NotImplemented error.

## Code changes
- Implemented a bulkImport function that returns a 202 status code and a content-location header
- Added a bulkstatus controller which manages the flow of bulk data import status requests.
- Exposed a /bulkstatus/:id endpoint which can receive requests for bulk import status updates, but for now just returns a 501 NotImplemented error. 

# Testing guidance
- check out Sarah's recent PR for information on how to send bulkImport requests [here](https://github.com/projecttacoma/deqm-test-server/pull/18).
- Send a bulkImport request and ensure that the response code is a `202` and that the headers contain a contain a `Content-Location` field which is set to `EXAMPLE-LOCATION`.
- Send a `GET` request to `http://localhost:3000/4_0_0/bulkstatus/EXAMPLE-LOCATION` and ensure you receive a 501 NotImplemented error.
- If you have input on how to avoid the hijinks I pull on line 162 of measure.service.js to get Asymmetrik not to overwrite the status code, please let me know

2021-09-27 19:53 UTC, sarahmcdougall commented on src/services/measure.service.js
>    logger.info('Measure >>> $bulk-import');
```suggestion
```

2021-09-27 19:54 UTC, sarahmcdougall commented on src/services/measure.service.js
>    logger.info('Measure >>> $bulk-import');
We have this logger.info included twice

2021-09-27 19:56 UTC, sarahmcdougall commented on src/services/measure.service.js
> + * TODO: implement bulk import stuff
```suggestion
 * TO-DO: add bulk import functionality
```

2021-09-27 19:59 UTC, sarahmcdougall requested changes
Good work! All the functionality works as expected. I just have a few suggested changes but nothing major. Unfortunately, I don’t really have a solution to the measure.service.js code for overwriting the status code :/ I think it suffices for now

2021-09-27 20:31 UTC, natjoe4 commented on src/services/measure.service.js
> + * TODO: implement bulk import stuff
I'll consider it...

2021-09-28 12:52 UTC, sarahmcdougall approved these changes
Everything looks good now, aside from the sass you've been giving me. Thanks for somewhat changing the comment back

2021-09-28 12:52 UTC, merged