Added Winston Debug and Info Logging
projecttacoma/deqm-test-server pull request #85
Opened 2022-02-09 17:47 UTC by natjoe4

# Summary
Added debug and info level logging through Winston to clarify the order or operations and assist with debugging.

## New behavior
- Running with NODE_ENV set to anything but 'debug' (defaults to 'production') will print only info-level logs
- Running with NODE_ENV set to 'debug' will print debug-level logs
- ndjsonWorker and importWorker now log using the existing logger instead of `console.log()`
- Logs will no longer print during unit tests

## Code changes
- Added a new .env variable to silence and trigger debug logging
- Added lots and lots of debug logging
- Added high-level info logging
- Added a jest config file to silence logging during unit tests

# Testing guidance
- Ensure all input and output to/from the server is unchanged
- Run using the command `NODE_ENV=debug npm start` and ensure all debug-level logs appear
- Run using `npm start` and ensure only info-level logs appear
- Run `npm test` and ensure no logs appear
- Look through all files and determine if all potentially useful info is logged or if any unnecessary info is logged

2022-02-09 20:31 UTC, mgramigna commented on src/util/validationUtils.js
> + * for missing parameters, the use of unsupported parameters, and the use of unsupported
And the student becomes the master

2022-02-09 20:33 UTC, natjoe4 commented on src/util/validationUtils.js
> + * for missing parameters, the use of unsupported parameters, and the use of unsupported
vs code spell checker baybeeee

2022-02-10 18:03 UTC, mgramigna requested changes
Looks great. Only a few small comments inline.

Note: We definitely take a performance hit in debug mode when we log FHIR libraries since that have huge b64-encoded strings on them (e.g. `$evaluate-measure` takes way longer). I think this performance hit is totally fine since since debug mode is not the default. Just wanted to note it here as long as you agree

2022-02-10 20:18 UTC, mgramigna approved these changes

2022-02-10 20:18 UTC, merged